### PR TITLE
doamin

### PR DESCRIPTION
**Pull request by oliik2013**

### CODE REVIEW

**Comment by oliik2013** [comment]
DKIM record is not supported?

**Comment by YazeedT** [comment]
Hello oliik. Can you please share exactly what do you need the subdomain for, so I can help you better?

**Comment by oliik2013** [comment]
I trying to use the domain for custom E-mail address

**Comment by YazeedT** [comment]
Our service does not support DKIM records.

But you don't need one to set up the necessary records for email. You will need a TXT and an MX record. You will add those records to the original JSON you submitted alongside your CNAME record.

I will close this PR and feel free to edit your original JSON to add the necessary MX and TXT records provided by your email host.

**Pull request closed without merging**
