### PR TITLE
Create wdh.thedev.me.json

### PR DESCRIPTION
**Pull request by williebenner**

### CODE REVIEW

**Comment by augustsav** [comment]
Hi?

**Comment by YazeedT** [comment]
Can you elaborate more on why you need so many subdomains? What kind of web applications will you be hosting?

**Comment by augustsav** [comment]
> Can you elaborate more on why you need so many subdomains? What kind of web applications will you be hosting?

I have quite a few web applications I want to test, I also have a lot of hosting to test them, I'm missing many subdomains. So, I hope you will help me. Thank

**Comment by YazeedT** [comment]
I need you to be more specific if you're asking for so many domains.

You already have NS records set for wfh.thedev.me, so you can set unlimited subdomains there for testing and your applications.

**Comment by augustsav** [comment]
Thank you, can you delete 4 new domains for me?

**Pull request closed without merging**
