### PR TITLE
Create xzonix.thedev.me.json

### PR DESCRIPTION
**Pull request by xzonix**

### CODE REVIEW

**Comment by YazeedT** [comment]
You can't have A and CNAME records at the same time. Leave only one of them.

Delete MX and TXT records too. You don't need them for your purpose.

**Comment by xzonix** [comment]
I need the MX and TXT records to have a personal email.

**Comment by YazeedT** [comment]
Alright, no problem. Update or delete the TXT record's value because you left it to the example.

**Comment by xzonix** [comment]
Alr, changes made!

**Pull request merged**
