### PR TITLE
Register send-me-a-message.thedev.me

### PR DESCRIPTION
**Pull request by divyanshudhruv**
Create send-me-a-message.thedev.me.json

### CODE REVIEW

**Comment by divyanshudhruv** [comment]
anyone ?

**Comment by EducatedSuddenBucket** [comment]
@divyanshudhruv blud cname can't have paths , close this pr and lean abt dns

**Comment by divyanshudhruv** [comment]
> @divyanshudhruv blud cname can't have paths , close this pr and lean abt dns

oh, my bad. sorry,

**Comment by EducatedSuddenBucket** [comment]
@divyanshudhruv close this pull request

**Comment by YazeedT** [comment]
Please remove the path from your CNAME record and I will approve your PR

**Comment by divyanshudhruv** [comment]
I appreciate that, but I already have a custom domain as "is-a.dev", so I think I have to pass it for now. But I'll look forward to this domain in the near future.

**Pull request closed without merging**
